### PR TITLE
Update linkedin url

### PR DESCRIPTION
**Pull request by abhishekgahlot**
Sam LinkedIn url was incorrect so fixed that :)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/website/10)

### CODE REVIEW

**Comment by manishrjain** [comment]
Thanks for the change. I think you have a mistake below, so fix that please.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[about.html, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/website/10#-Kq1Edp2lpYir3w62gOW:-Kq1Edp2lpYir3w62gOX:b-cx242q) ([raw file](https://github.com/dgraph-io/website/blob/ffa958b80d51a53c0f351d174701674065cf756c/about.html#L265)):*
> ```HTML
>           <div class="col-12 col-desktop-6">
>             <div class="member">
>               <div class="member__figure"><img src="assets/images/about/team-sam.jpg" alt="Image of 
> ```

You also removed the `Image of "Sam"`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/website/10#-:-Kq1EhqI8kzhuRwdbXoH:b6dcq5q)*

**Comment by abhishekgahlot** [comment]
Fixed it now.

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/website/10#-:-Kq1GAqcI6McIAMGpdyJ:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[about.html, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/website/10#-Kq1Edp2lpYir3w62gOW:-Kq1GKY5VWGlTBthUoRa:b32w0x) ([raw file](https://github.com/dgraph-io/website/blob/ffa958b80d51a53c0f351d174701674065cf756c/about.html#L265)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You also removed the `Image of "Sam"`?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/website/10)*

**Pull request merged**
