### PR TITLE
add code folding for results json editor

### PR DESCRIPTION
**Pull request by NorikDavtian**
the results json data is too long and it is hard to read.
enabling the code folding makes it much easier to read the results and make sense of the returned data structure.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/website/11)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Looks like a great change. Will review when I get to work tomorrow.

**Comment by pawanrawal** [comment]
Works great. I see you removed a bunch of `webkit-*` from the CSS. Why is that so?

**Comment by NorikDavtian** [comment]
it was automatically generated with the grunt.. do you want me to revert those changes?

**Comment by pawanrawal** [comment]
LGTM, merged!

**Pull request merged**
